export const languages = [
    { name: 'EN', flag: '🇬🇧' },
    { name: 'ES', flag: '🇪🇸' },
    { name: 'IT', flag: '🇮🇹' },
    { name: 'DU', flag: '🇳🇱' },
    { name: 'FR', flag: '🇫🇷' },
    { name: 'PT', flag: '🇵🇹' },
    { name: 'DE', flag: '🇩🇪' },
    { name: 'DA', flag: '🇩🇰' },
    { name: 'RU', flag: '🇷🇺' },
    { name: 'KO', flag: '🇰🇷' },
    { name: 'CH', flag: '🇨🇳' },
    { name: 'JP', flag: '🇯🇵' },
    { name: 'AR', flag: '🇸🇦' },
    { name: 'HI', flag: '🇮🇳' },
    // { name: 'CA', flag: 'CT' },
  ];  