export const logos = {
    'zara': "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Zara_Logo.svg/320px-Zara_Logo.svg.png",
    'mango': "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Logo_of_Mango_%28new%29.svg/320px-Logo_of_Mango_%28new%29.svg.png",
    'uo': "https://seeklogo.com/images/U/urban-outfitters-logo-E9B99ABE57-seeklogo.com.png",
    'h&m': "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/H%26M-Logo.svg/320px-H%26M-Logo.svg.png",
    'cos': "https://www.pacificplace.com.hk/-/media/images/pacificplace2/shops/logo/cos-logo-oct2021.ashx?rev=e3043e5ac57d41809a74ad6b271492ec&hash=9b49f1eefd0452d56bb18002a66363d3",
    'massimo dutti': "https://upload.wikimedia.org/wikipedia/commons/7/74/Massimo_Dutti.png",
    'pull & bear': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Pull%26Bear_logo.svg/2560px-Pull%26Bear_logo.svg.png?20171102004503',
    'bershka': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Bershka_logo.svg/2560px-Bershka_logo.svg.png',
    'stradivarius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Stradivarius_logo.svg/2560px-Stradivarius_logo.svg.png',
    '&other': 'https://upload.wikimedia.org/wikipedia/commons/8/8e/%26_Other_Stories_logo.png',
    'desigual': 'https://torrado.es/wp-content/uploads/2023/02/kisspng-desigual-logo-clothing-brand-fashion-license-commercial-5b12ecb04ec483.8944058915279668963227.png',
    'uniqlo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Uniqlo_logo_Japanese.svg/1600px-Uniqlo_logo_Japanese.svg.png',
    'ben sherman': 'https://cdn.shopify.com/s/files/1/0492/7438/8634/files/Signature_BS_Logo_Navy.png?v=1631691641',
    'loewe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Loewe_logo.svg/2560px-Loewe_logo.svg.png',
    'adidas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/1600px-Adidas_Logo.svg.png',
    'moschino': 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Moschino_logo.svg',
    'farm rio': 'https://logodownload.org/wp-content/uploads/2020/10/farm-rio-logo.png',
    'miu miu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Miu-Miu-Logo.svg/2560px-Miu-Miu-Logo.svg.png',
    'calvin klein': 'https://logos-download.com/wp-content/uploads/2016/02/Calvin_Klein_logo.png',
    'balenciaga': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Balenciaga2017Logo.svg/2560px-Balenciaga2017Logo.svg.png',
    'champion': 'https://upload.wikimedia.org/wikipedia/commons/3/39/Champion_Usa_logo.png',
    'dior': 'https://upload.wikimedia.org/wikipedia/commons/5/56/Dior_Logo_2022.svg',
    'all saints': 'https://fashionunited.com/img/upload/2022/08/09/allsaints-logo-yyvp0b72-2022-06-17-3sfad3sg-2022-08-09.png',
    'alexander mcqueen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Logo_of_Alexander_McQueen.svg/2560px-Logo_of_Alexander_McQueen.svg.png',
    'fila': 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Fila_logo.svg',
    'sandro': 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Sandro-logo.jpg',
    'ysl':'https://upload.wikimedia.org/wikipedia/commons/2/29/Yves_Saint_Laurent_Logo.svg',
    'parfois': 'https://upload.wikimedia.org/wikipedia/commons/2/2b/ParfoisLogo.jpg',
    'hugo boss': 'https://upload.wikimedia.org/wikipedia/commons/7/73/Hugo-Boss-Logo.svg',
    'hyein seo':'https://www.ink-clothing.com/category/XrVGHs4cbTcWxgor.jpg'
  };