import Head from 'next/head';
import NavBar from './NavBar';
import React ,{ useState } from 'react';
import { initFirebase } from "../../services/firebase";
import { getAuth } from "firebase/auth";
import { useAuthState } from 'react-firebase-hooks/auth';
import { logOutExternal } from '../Auth/logOutExternal';
import { signInGoogleExternal } from '../Auth/signInWithGoogleExternal';
import { getFirestore } from "firebase/firestore";
import LogInModal from '../Auth/LogInModal';


const Layout = ({ children }) => {
  const app = initFirebase();  // Initialize Firebase
  const db = getFirestore(app); // Initialize database
  // const analytics = getAnalytics(app); // Initialize Analytics and get a reference to the service
  const auth = getAuth(); // instance of auth method
  const [user, loading] = useAuthState(auth); // user data
  const signInGoogle = () => { // runs the external sign in with google function
    signInGoogleExternal(auth,db)
  };
  const logOut = () => { // runs the external log out function
    logOutExternal(auth)
  };
  const [logInFlag , setLogInFlag] = useState(false); // log in flag for showing modal

  return (
    <div className='w-screen h-screen flex flex-col bg-dokuso-white'>
      <Head>
        <title>Dokusō</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <NavBar signInGoogle={signInGoogle} logOut={logOut} user={user} setLogInFlag={setLogInFlag}/>
      <main className='flex flex-col flex-auto p-0 m-0 overflow-auto scrollbar'>
        {children}
        {logInFlag && <LogInModal setLogInFlag={setLogInFlag} logInFlag={logInFlag}/>}
      </main>
    </div>
  )
}

export default Layout;